### ISSUE TITLE
Enhancement request: Split only paths that have changed

### ISSUE THREAD

**Issue by redthor** [jderusse/docker-gitsplit#12]
It would be good if we could optionally pass `gitsplit` an environment variable that is a git revision comparison spec. e.g. `7b0d7d5` or `7b0d7d5..c262a9e`.

If the env var is found `gitsplit` will compare the tree changes between the revisions (or HEAD if only a SHA given). Using the comparison `gitsplit` will only process splits where the prefix matches the tree changes.

For example. Given this config:

```
splits:
  - prefix: "src/partA"
    target: "https://${GH_TOKEN}@github.com/my_company/project-partA.git"
  - prefix: "src/partB"
    target: "https://${GH_TOKEN}@github.com/my_company/project-partB.git"
  - prefix: "src/partC"
    target: "https://${GH_TOKEN}@github.com/my_company/project-partC.git"
```

We find out what has changed:
`git diff --name-only REV`
```
src/partC/README.md
src/partC/src/MyCompany/ClassA.php
src/partC/src/MyCompany/ClassB.php
```
gitsplit processing is only for that prefix that matches (`src/partC`):
```
Fetching https://github.com/my_company/project-partC.git
Splitting refs/heads/master for src/partC
Pushing refs/heads/master into https://github.com/my_company/project-partC.git
```

For us this could significantly speed up the process.
I'm not sure how difficult it is to implement, or perhaps there is another solution.

thanks.
